<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-FK5U4VG9" ignored="0" name="Test" tests="5" failures="1" timestamp="02 May 2020 06:35:50 GMT" time="15.896" errors="0">
  <testcase name="verifyGetCallBody" time="1.096" classname="com.qa.test.apiTestGetCall">
    <skipped/>
  </testcase> <!-- verifyGetCallBody -->
  <testcase name="verifyGetCallBody" time="0.097" classname="com.qa.test.apiTestGetCall">
    <skipped/>
  </testcase> <!-- verifyGetCallBody -->
  <testcase name="verifyGetCallBody" time="0.143" classname="com.qa.test.apiTestGetCall">
    <failure type="java.lang.AssertionError" message="Response is incorrect  expected [230 Degree] but found [180 Degree]">
      <![CDATA[java.lang.AssertionError: Response is incorrect  expected [230 Degree] but found [180 Degree]
at com.qa.test.apiTestGetCall.verifyGetCallBody(apiTestGetCall.java:51)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- verifyGetCallBody -->
  <testcase name="verifyGetCallStatus" time="0.002" classname="com.qa.test.apiTestGetCall"/>
  <testcase name="verifyHeadersGetCall" time="0.003" classname="com.qa.test.apiTestGetCall"/>
</testsuite> <!-- Test -->
